"""
Space Invader Template - Configurable settings for the game.
Adjust these values to customize gameplay without changing game logic.
"""

SCREEN_WIDTH = 200
SCREEN_HEIGHT = 180

BACKGROUND_COLOR = 0

PLAYER_SPEED = 2
PLAYER_COLOR = 7
PLAYER_WIDTH = 16
PLAYER_HEIGHT = 8

BULLET_SPEED = 4
BULLET_COLOR = 10
BULLET_WIDTH = 2
BULLET_HEIGHT = 6
PLAYER_FIRE_RATE = 15

ENEMY_ROWS = 3
ENEMY_COLS = 8
ENEMY_SPEED = 0.5
ENEMY_SPEED_INCREMENT = 0.1
ENEMY_DROP_AMOUNT = 4
ENEMY_COLOR = 8
ENEMY_WIDTH = 8
ENEMY_HEIGHT = 8
ENEMY_SCORE = 10

ENEMY_BULLET_SPEED = 2
ENEMY_BULLET_COLOR = 8
ENEMY_FIRE_RATE = 60

EXPLOSION_DURATION = 10
EXPLOSION_COLOR = 9

LIVES = 3
START_LEVEL = 1
SCORE_DISPLAY_X = 5
SCORE_DISPLAY_Y = 5
LIVES_DISPLAY_X = 150
LIVES_DISPLAY_Y = 5
LEVEL_DISPLAY_X = 80
LEVEL_DISPLAY_Y = 5

ENEMY_FORMATIONS = ["classic", "diamond", "circle"]
DEFAULT_FORMATION = "classic"
